site_name: Documentações SPF

nav:
  - Home: index.md

  - Documentações:
      - Power Automate Desktop: automate_desktop.md
      - Power BI: pbi.md

  - Projetos:
      - Painel Execução Orçamentária - DPO: https://app.powerbi.com/view?r=eyJrIjoiMGUwMmRmN2MtY2YwMy00MmMwLTllNDItNTc1ZjA4NDdjNzE5IiwidCI6ImU1ZDNhZTdjLTliMzgtNDhkZS1hMDg3LWY2NzM0YTI4NzU3NCJ9
      - Painel Contratos - DCC: https://app.powerbi.com/view?r=eyJrIjoiNjM1OGU2ODUtNGY1Yy00MjBiLTgwZTItZDM1ZGZjMTlkNjlhIiwidCI6ImU1ZDNhZTdjLTliMzgtNDhkZS1hMDg3LWY2NzM0YTI4NzU3NCJ9&pageName=0250f26b7a42d7cc6766
      - Painel PAC 2025 - DCCC: https://app.powerbi.com/view?r=eyJrIjoiNjgxYmE0OTctMWVkMi00NWNkLTllZjctYmY5ZGIwNTdiMzI0IiwidCI6ImU1ZDNhZTdjLTliMzgtNDhkZS1hMDg3LWY2NzM0YTI4NzU3NCJ9&pageName=a193727a160379368e49
      - Fluxo Pagamento Notas Fiscais: https://cecad365.sharepoint.com/:f:/r/sites/AutomatizacoesSPF/Documentos%20Compartilhados/General/dcf/fluxos/Registrar%20NFS%202.0?csf=1&web=1&e=UhQpDL
      - Fluxo Liquidação: https://cecad365.sharepoint.com/:f:/r/sites/AutomatizacoesSPF/Documentos%20Compartilhados/General/dcf/fluxos/Registrar%20Liquida%C3%A7%C3%A3o%202.0?csf=1&web=1&e=YfUYau
      - Fluxo Registro de Empenho: https://cecad365.sharepoint.com/:f:/r/sites/AutomatizacoesSPF/Documentos%20Compartilhados/General/dcf/fluxos/Registrar%20Empenho?csf=1&web=1&e=SZKQKr
      - Fluxo Emissão Guia ISSQN: https://cecad365.sharepoint.com/:f:/r/sites/AutomatizacoesSPF/Documentos%20Compartilhados/General/dcf/fluxos/Emitir%20Guia%20ISSQN?csf=1&web=1&e=Mtf5YC
      - Fluxo Extração Ordens de Pagamento SEDE: https://cecad365.sharepoint.com/:f:/r/sites/AutomatizacoesSPF/Documentos%20Compartilhados/General/sede?csf=1&web=1&e=amAVIG

  - Quem Somos: quem_somos.md

theme:
  name: material
  features:
    - navigation.sections

# Carrega seu CSS customizado (com as regras de toggle e grid de cards)
extra_css:
  - assets/stylesheets/custom.css

# Carrega o JS que faz o AJAX e o toggle do menu
extra_javascript:
  - ajax-nav.js

markdown_extensions:
  - attr_list
  - md_in_html
