site_name: Documentações SPF

nav:
  - Home: index.md
  
  - Documentações:
      - Power Automate Desktop: automate_desktop_documentacoes.md
      - Power Automate Web: documentacoes_automate_web.md
      - Power BI: pbi_documentacao.md
      - Python: documentacoes_py.md
      

  - Projetos:
      - Power Automate Desktop: fluxos_automate.md
      - Power Automate Web: fluxos_automate_web.md
      - Power BI: projetos_bi.md
      - Python: projetos_py.md
      
  - Quem Somos: quem_somos.md

theme:
  name: material
  features:
    - navigation.instant
    

# Carrega seu CSS customizado (com as regras de toggle e grid de cards)
extra_css:
  - align.image.css

# Carrega o JS que faz o AJAX e o toggle do menu
extra_javascript:
  - ajax-nav.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details

plugins: 
 - glightbox
  

  
